#ifndef EVENT_SOURCE_H_
#define EVENT_SOURCE_H_

#include <esp_event.h>
#include <esp_timer.h>

ESP_EVENT_DECLARE_BASE(COMMAND_EVENTS);

enum {
    COMMAND_EVENT_TIMER_EXPIRY,
    COMMAND_EVENT_CAMERA_CAPTURE
};

ESP_EVENT_DECLARE_BASE(MESSAGE_EVENTS);

enum {
    MESSAGE_EVENT_NEW_DEBUG,
    MESSAGE_EVENT_NEW_TEMP,
    MESSAGE_EVENT_NEW_HUMIDITY,
    MESSAGE_EVENT_NEW_SOIL,
};

#endif